// Araba fotoğraflarının kaynak ve lisans bilgisi.
//
// Hepsi Wikimedia Commons'tan, hepsi serbest lisanslı (CC0, CC BY, CC BY-SA
// veya kamu malı). Dosyalar public/arabalar/ altında duruyor; dışarıdan
// resim çekilmiyor.
//
// Burası tek kaynak: seed/seed.mjs items tablosunun image_url ve
// image_credit alanlarını buradan doldurur, /atif sayfası da buradan
// beslenir. Yeni araba eklerken fotoğrafı buraya da yaz.

export const PHOTOS = {
  "peugeot-205-gti-19": {
    file: "/arabalar/peugeot-205-gti-19.jpg",
    artist: "Vauxford",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1990_Peugeot_205_GTi_1.6_Front.jpg",
  },
  "vw-golf-gti-mk2": {
    file: "/arabalar/vw-golf-gti-mk2.jpg",
    artist: "Riley",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1987_Volkswagen_Golf_GTi_(31488973161).jpg",
  },
  "renault-5-gt-turbo": {
    file: "/arabalar/renault-5-gt-turbo.jpg",
    artist: "Vauxford",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1991_Renault_5_GT_Turbo_1.4_Front.jpg",
  },
  "honda-civic-vti-eg6": {
    file: "/arabalar/honda-civic-vti-eg6.jpg",
    artist: "Toyotacoronaexsaloon",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Honda_civic_eg6_sirii_1_f.jpg",
  },
  "renault-clio-williams": {
    file: "/arabalar/renault-clio-williams.jpg",
    artist: "Guillaume Vachey",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Renault_Clio_Williams_(40965508772).jpg",
  },
  "peugeot-306-gti-6": {
    file: "/arabalar/peugeot-306-gti-6.jpg",
    artist: "Calreyn88",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1999_Peugeot_306_GTi.jpg",
  },
  "porsche-911-964-carrera-2": {
    file: "/arabalar/porsche-911-964-carrera-2.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Porsche_964_Carrera_2_coup%C3%A9_front.JPG",
  },
  "ferrari-348-tb": {
    file: "/arabalar/ferrari-348-tb.jpg",
    artist: "Guillaume Vachey",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ferrari_348_tb_(43496139042).jpg",
  },
  "honda-nsx-na1": {
    file: "/arabalar/honda-nsx-na1.jpg",
    artist: "先従隗始",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Honda_E-NA1_NSX_(22022010314).jpg",
  },
  "dodge-viper-rt10": {
    file: "/arabalar/dodge-viper-rt10.jpg",
    artist: "MercurySable99",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1995_Dodge_Viper_RT_10,_front_left,_09-30-2023.jpg",
  },
  "chevrolet-corvette-zr1-c4": {
    file: "/arabalar/chevrolet-corvette-zr1-c4.jpg",
    artist: "Calreyn88",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1992_Chevrolet_Corvette_C4_ZR-1.jpg",
  },
  "porsche-928-gts": {
    file: "/arabalar/porsche-928-gts.jpg",
    artist: "Mr.choppers",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1993_Porsche_928_GTS_in_Wimbledon_Green,_front_right.jpg",
  },
  "bmw-m3-e30": {
    file: "/arabalar/bmw-m3-e30.jpg",
    artist: "Handelsgeselschaft",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BMW_M3_E30,_Pau_2015_2.jpg",
  },
  "mercedes-190e-25-16": {
    file: "/arabalar/mercedes-190e-25-16.jpg",
    artist: "Pitak",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_W201_190E_2.5-16_jaslo1.jpg",
  },
  "alfa-romeo-75-twin-spark": {
    file: "/arabalar/alfa-romeo-75-twin-spark.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:The_frontview_of_Alfa_Romeo_75_TWIN_SPARK.JPG",
  },
  "bmw-m5-e34": {
    file: "/arabalar/bmw-m5-e34.jpg",
    artist: "nakhon100",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BMW_M5_E34_(4891495611).jpg",
  },
  "mercedes-500e-w124": {
    file: "/arabalar/mercedes-500e-w124.jpg",
    artist: "Mr.choppers",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1992_Mercedes-Benz_500E_(W124.036),_front_right.jpg",
  },
  "audi-s4-c4": {
    file: "/arabalar/audi-s4-c4.jpg",
    artist: "FotoSleuth",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Audi_S4.jpg",
  },
  "opel-astra-g": {
    file: "/arabalar/opel-astra-g.jpg",
    artist: "M 93",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Opel_Astra_G_front.JPG",
  },
  "fiat-bravo-182": {
    file: "/arabalar/fiat-bravo-182.jpg",
    artist: "Corvettec6r",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fiat_Bravo_1.4_12V.JPG",
  },
  "peugeot-307": {
    file: "/arabalar/peugeot-307.jpg",
    artist: "Vauxford",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2002_Peugeot_307_Rapier_16V_1.6_Front.jpg",
  },
  "hyundai-accent-era": {
    file: "/arabalar/hyundai-accent-era.jpg",
    artist: "IFCAR",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hyundai-Accent-GS-front.jpg",
  },
  "fiat-albea": {
    file: "/arabalar/fiat-albea.jpg",
    artist: "Raf24",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fiat_Albea_front,_PIA.jpg",
  },
  "chevrolet-aveo-t250": {
    file: "/arabalar/chevrolet-aveo-t250.jpg",
    artist: "IFCAR",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2007-Chevrolet-Aveo-1.jpg",
  },
  "lancia-delta-hf-integrale-evo": {
    file: "/arabalar/lancia-delta-hf-integrale-evo.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:The_frontview_of_1st_generation_Lancia_DELTA_HF_Integrale_16V_Evoluzione.JPG",
  },
  "ford-sierra-rs-cosworth": {
    file: "/arabalar/ford-sierra-rs-cosworth.jpg",
    artist: "Aethonatic",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ford_Sierra_RS_Cosworth_(RS_500)_-_10_August_2025.jpg",
  },
  "audi-quattro": {
    file: "/arabalar/audi-quattro.jpg",
    artist: "Ross",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Audi_Ur-Quattro_(9532193009).jpg",
  },
  "subaru-impreza-22b-sti": {
    file: "/arabalar/subaru-impreza-22b-sti.jpg",
    artist: "MrWalkr",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1998_Subaru_Impreza_22b_STi.jpg",
  },
  "mitsubishi-lancer-evo-vi-tme": {
    file: "/arabalar/mitsubishi-lancer-evo-vi-tme.jpg",
    artist: "Oq10pass",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mitsubishi_Lancer_Evolution_VI_T.M._Edition_%2700.jpg",
  },
  "toyota-celica-gt-four-st205": {
    file: "/arabalar/toyota-celica-gt-four-st205.jpg",
    artist: "Fogarin at English Wikipedia",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:GT-FOUR_ST205.jpg",
  },
  "togg-t10x": {
    file: "/arabalar/togg-t10x.jpg",
    artist: "Matti Blume",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Togg_T10X,_IAA_Mobility_2025,_Munich_(20250909-P1050619).jpg",
  },
  "fiat-egea": {
    file: "/arabalar/fiat-egea.jpg",
    artist: "Jakub \"Flyz1\" Maciejewski",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fiat_Tipo_-_prz%C3%B3d_(MSP16).jpg",
  },
  "renault-clio-5": {
    file: "/arabalar/renault-clio-5.jpg",
    artist: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Renault_Clio_V_1X7A0393.jpg",
  },
  "peugeot-208-2019": {
    file: "/arabalar/peugeot-208-2019.jpg",
    artist: "Vauxford",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2020_Peugeot_208_GT_Line_PureTech_1.2_Front.jpg",
  },
  "toyota-corolla-e210": {
    file: "/arabalar/toyota-corolla-e210.jpg",
    artist: "JamesYoung8167",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Toyota_Corolla_E210_sedan_Shishi_01_2022-06-13.jpg",
  },
  "dacia-duster-2018": {
    file: "/arabalar/dacia-duster-2018.jpg",
    artist: "(G)jabz",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Dacia_Duster_Mk2_-_Front_View.jpg",
  },
  "tesla-model-3": {
    file: "/arabalar/tesla-model-3.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tesla_Model_3_(2023)_Autofr%C3%BChling_Ulm_IMG_9282.jpg",
  },
  "tesla-model-y": {
    file: "/arabalar/tesla-model-y.jpg",
    artist: "Daniel.Cardenas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tesla_Model_Y_front_passenger_side_view.jpg",
  },
  "hyundai-ioniq-5": {
    file: "/arabalar/hyundai-ioniq-5.jpg",
    artist: "crash71100",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2021_Hyundai_Ioniq_5_(France)_front_view.jpg",
  },
  "kia-ev6": {
    file: "/arabalar/kia-ev6.jpg",
    artist: "Jan Ainali",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kia-EV6-front-left.jpg",
  },
  "vw-id4": {
    file: "/arabalar/vw-id4.jpg",
    artist: "Dennis Elzinga",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2020_Volkswagen_ID.4_Pro_(Netherlands)_front_view.jpg",
  },
  "byd-atto-3": {
    file: "/arabalar/byd-atto-3.jpg",
    artist: "Hubert Berberich (HubiB)",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BYD_Atto_3_front-left.jpg",
  },
  "toyota-gr-yaris": {
    file: "/arabalar/toyota-gr-yaris.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Toyota_GR_Yaris_RZ_(2020)_IMG_9308.jpg",
  },
  "honda-civic-type-r-fl5": {
    file: "/arabalar/honda-civic-type-r-fl5.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Honda_Civic_Type_R_FL5_in_Championship_White,_front_left,_06-30-2024.jpg",
  },
  "vw-golf-8-gti": {
    file: "/arabalar/vw-golf-8-gti.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Volkswagen_Golf_VIII_GTI_Facelift_IMG_0426.jpg",
  },
  "hyundai-i20-n": {
    file: "/arabalar/hyundai-i20-n.jpg",
    artist: "Aethonatic",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hyundai_i20_N_(A25_TBS)_-_7_June_2026.jpg",
  },
  "renault-megane-rs": {
    file: "/arabalar/renault-megane-rs.jpg",
    artist: "Vauxford",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2019_Renault_Megane_R.S._300_Trophy_1.8_Front.jpg",
  },
  "mini-jcw": {
    file: "/arabalar/mini-jcw.jpg",
    artist: "Wikisympathisant",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mini_Hatch_(F56)_John_Cooper_Works_3-4-front_2025-08.jpg",
  },
  "bmw-m3-g80": {
    file: "/arabalar/bmw-m3-g80.jpg",
    artist: "Alexandre Prevot",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BMW_M3_G80_(54544604786).jpg",
  },
  "audi-rs3-8y": {
    file: "/arabalar/audi-rs3-8y.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Audi_RS3_8Y_IMG_8404.jpg",
  },
  "mercedes-amg-a45-s": {
    file: "/arabalar/mercedes-amg-a45-s.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mercedes-AMG_A_45_S_4MATIC%2B_(W177)_front.jpg",
  },
  "porsche-911-992": {
    file: "/arabalar/porsche-911-992.jpg",
    artist: "Calreyn88",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2022_Porsche_911_992_Carrera_GTS.jpg",
  },
  "alpine-a110": {
    file: "/arabalar/alpine-a110.jpg",
    artist: "Andrew Basterfield",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alpine_A110_(35862764524).jpg",
  },
  "toyota-gr-supra": {
    file: "/arabalar/toyota-gr-supra.jpg",
    artist: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:D%C3%BClmen,_Auto_Bertels,_Toyota_GR_Supra_--_2021_--_9539.jpg",
  },
  "tofas-sahin": {
    file: "/arabalar/tofas-sahin.jpg",
    artist: "Mr.choppers",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tofa%C5%9F_Murat_131_%C5%9Eahin_1300.jpg",
  },
  "renault-megane-sedan": {
    file: "/arabalar/renault-megane-sedan.jpg",
    artist: "Rutger van der Maar",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Renault_M%C3%A9gane_sedan_(Romania)_front_view.jpg",
  },
  "hyundai-i20-bc3": {
    file: "/arabalar/hyundai-i20-bc3.jpg",
    artist: "Damian B Oh",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hyundai_i20_1.0_T-GDi_48V_MHEV_BC3_Atlas_White_(1).jpg",
  },
  "toyota-chr": {
    file: "/arabalar/toyota-chr.jpg",
    artist: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Toyota_C-HR_hybrid_(FL)_1X7A6305.jpg",
  },
  "vw-polo-6": {
    file: "/arabalar/vw-polo-6.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Volkswagen_POLO_TSI_Trendline_(3BA-AWDKL)_front.jpg",
  },
  "opel-corsa-f": {
    file: "/arabalar/opel-corsa-f.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Opel_Corsa_F_IMG_8196.jpg",
  },
  "peugeot-301": {
    file: "/arabalar/peugeot-301.jpg",
    artist: "User3204",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2017_Peugeot_301_(facelift,_front).jpg",
  },
  "skoda-octavia-4": {
    file: "/arabalar/skoda-octavia-4.jpg",
    artist: "Mike-fiesta",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Skoda_Octavia_IV_liftback.jpg",
  },
  "nissan-qashqai-j12": {
    file: "/arabalar/nissan-qashqai-j12.jpg",
    artist: "Kazyakuruma",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nissan_Qashqai,_2021,_in_Nissan_Global_HQ_Gallery,_front.jpg",
  },
  "ford-focus-mk4": {
    file: "/arabalar/ford-focus-mk4.jpg",
    artist: "Vauxford",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2018_Ford_Focus_Vignale_Front.jpg",
  },
  "dacia-sandero-3": {
    file: "/arabalar/dacia-sandero-3.jpg",
    artist: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Dacia_Sandero_III_1X7A6451.jpg",
  },
  "hyundai-bayon": {
    file: "/arabalar/hyundai-bayon.jpg",
    artist: "Rutger van der Maar",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2021_Hyundai_Bayon_1.0_T-GDi_48V_front.jpg",
  },
  "fiat-egea-cross": {
    file: "/arabalar/fiat-egea-cross.jpg",
    artist: "Anthony Levrot",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rotterdam_-_3072_-_2024.01.07_-_Enterprise_Rent-A-Car_-_Fiat_Tipo_(vue_avant_gauche)_%C2%A9_Anthony_Levrot.jpg",
  },
  "togg-t10f": {
    file: "/arabalar/togg-t10f.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Togg_T10F_IAA_2025_DSC_2140.jpg",
  },
  "byd-seal": {
    file: "/arabalar/byd-seal.jpg",
    artist: "Matti Blume",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BYD_Seal,_IAA_Open_Space_2023,_Munich_(P1120203).jpg",
  },
  "xiaomi-su7": {
    file: "/arabalar/xiaomi-su7.jpg",
    artist: "Benlisquare",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Xiaomi_SU7_with_Tianjin_plates,_lower_angle_from_front.jpg",
  },
  "porsche-taycan": {
    file: "/arabalar/porsche-taycan.jpg",
    artist: "Dinkun Chen",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:PORSCHE_TAYCAN_China_(2).jpg",
  },
  "polestar-2": {
    file: "/arabalar/polestar-2.jpg",
    artist: "Matti Blume",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Polestar_2,_GIMS_2019,_Le_Grand-Saconnex_(GIMS0552).jpg",
  },
  "bmw-i4": {
    file: "/arabalar/bmw-i4.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BMW_i4_eDrive40_M_Sport_(G26)_front.jpg",
  },
  "skoda-enyaq": {
    file: "/arabalar/skoda-enyaq.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%C5%A0koda_Enyaq_IMG_1190.jpg",
  },
  "volvo-ex30": {
    file: "/arabalar/volvo-ex30.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Volvo_EX30_1X7A2476.jpg",
  },
  "mg4": {
    file: "/arabalar/mg4.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:MG4_EV_IMG_9349.jpg",
  },
  "renault-megane-etech": {
    file: "/arabalar/renault-megane-etech.jpg",
    artist: "(G)jabz",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Renault_Megane_E-Tech_-_Front_View.jpg",
  },
  "cupra-born": {
    file: "/arabalar/cupra-born.jpg",
    artist: "Harvey Bold",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2023_Cupra_Born_V1_EV_-_58kWh_(203PS)_Electric_-_Glacial_White_-_07-2024,_Front.jpg",
  },
  "ford-mustang-mach-e": {
    file: "/arabalar/ford-mustang-mach-e.jpg",
    artist: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ford_Mustang_Mach-E_X_DSC_9357.jpg",
  },
  "ford-fiesta-st-mk8": {
    file: "/arabalar/ford-fiesta-st-mk8.jpg",
    artist: "Vauxford",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2018_Ford_Fiesta_ST-2_Turbo_1.5_Front_(1).jpg",
  },
  "hyundai-i30-n": {
    file: "/arabalar/hyundai-i30-n.jpg",
    artist: "MoCars",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2019_Hyundai_i30_Hatchback_N_Performance_(Front).jpg",
  },
  "cupra-leon": {
    file: "/arabalar/cupra-leon.jpg",
    artist: "Calreyn88",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2021_Cupra_Leon_VZ1_TSi.jpg",
  },
  "toyota-gr-corolla": {
    file: "/arabalar/toyota-gr-corolla.jpg",
    artist: "MercurySable99",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Toyota_GR_Corolla_Circuit_Edition,_front_left,_06-08-2024.jpg",
  },
  "honda-civic-type-r-fk8": {
    file: "/arabalar/honda-civic-type-r-fk8.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2017_Honda_Civic_Type_R_FK8_in_Championship_White,_front_right,_08-04-2024.jpg",
  },
  "abarth-595": {
    file: "/arabalar/abarth-595.jpg",
    artist: "Handelsgeselschaft",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Abarth_595_Competizione_front_1.jpg",
  },
  "bmw-m135i-f40": {
    file: "/arabalar/bmw-m135i-f40.jpg",
    artist: "NaBUru38",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BMW_M135i_xDrive_(F40)_at_BMW_Welt_-_front_right_view_(cropped).jpg",
  },
  "audi-s3-8y": {
    file: "/arabalar/audi-s3-8y.jpg",
    artist: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Audi_S3_8Y_IMG_4079.jpg",
  },
  "renault-clio-rs-4": {
    file: "/arabalar/renault-clio-rs-4.jpg",
    artist: "Luc106",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Renault_Clio-IV-RS_Front.JPG",
  },
  "ford-focus-st-mk4": {
    file: "/arabalar/ford-focus-st-mk4.jpg",
    artist: "Calreyn88",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2019_Ford_Focus_ST_1.jpg",
  },
  "peugeot-208-gti": {
    file: "/arabalar/peugeot-208-gti.jpg",
    artist: "Overlaet",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Peugeot_208_GTi_(front_quarter).JPG",
  },
  "suzuki-swift-sport": {
    file: "/arabalar/suzuki-swift-sport.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Suzuki_SWIFT_Sport_(CBA-ZC33S-VBRK)_front.jpg",
  },
  "nissan-gtr-r35": {
    file: "/arabalar/nissan-gtr-r35.jpg",
    artist: "MrWalkr",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nissan_R35_GT-R_in_Nottingham.jpg",
  },
  "corvette-c8": {
    file: "/arabalar/corvette-c8.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chevrolet_Corvette_C8_IMG_2537.jpg",
  },
  "ford-mustang-s550": {
    file: "/arabalar/ford-mustang-s550.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ford_MUSTANG_GT_50_Year_Limited_Edition_(S550).jpg",
  },
  "bmw-m2-g87": {
    file: "/arabalar/bmw-m2-g87.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_BMW_M2_G87,_front_left,_05-31-2024.jpg",
  },
  "porsche-cayman-gt4": {
    file: "/arabalar/porsche-cayman-gt4.jpg",
    artist: "MrWalkr",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2020_Porsche_718_Cayman_GT4_SCD_24.jpg",
  },
  "lotus-emira": {
    file: "/arabalar/lotus-emira.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lotus_Emira_IMG_8023.jpg",
  },
  "aston-martin-vantage": {
    file: "/arabalar/aston-martin-vantage.jpg",
    artist: "Mr.choppers",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2019_Aston_Martin_Vantage,_front_right_view_(Greenwich_2018).jpg",
  },
  "ferrari-296-gtb": {
    file: "/arabalar/ferrari-296-gtb.jpg",
    artist: "Calreyn88",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ferrari_296_GTB_(51370).jpg",
  },
  "lamborghini-huracan": {
    file: "/arabalar/lamborghini-huracan.jpg",
    artist: "Matti Blume",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lamborghini_Huracan_Perfomante,_IAA_2017,_Frankfurt_(1Y7A2082).jpg",
  },
  "mclaren-720s": {
    file: "/arabalar/mclaren-720s.jpg",
    artist: "Ermell",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mclaren_720S_PA280973-PSD.jpg",
  },
  "audi-r8-4s": {
    file: "/arabalar/audi-r8-4s.jpg",
    artist: "Damian B Oh",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Audi_R8_V10_Performance_4S_FL_Java_Green_Metallic_(2).jpg",
  },
  "mercedes-amg-gt": {
    file: "/arabalar/mercedes-amg-gt.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mercedes-AMG_GT_R_(C190)_front.jpg",
  },
  "opel-astra-j": {
    file: "/arabalar/opel-astra-j.jpg",
    artist: "M 93",
    license: "CC BY-SA 3.0 de",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Opel_Astra_(J)_%E2%80%93_Frontansicht,_21._Juni_2011,_Heiligenhaus.jpg",
  },
  "ford-focus-mk3": {
    file: "/arabalar/ford-focus-mk3.jpg",
    artist: "M 93",
    license: "CC BY-SA 3.0 de",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ford_Focus_Trend_(III)_%E2%80%93_Frontansicht,_17._September_2011,_Ratingen.jpg",
  },
  "renault-megane-3": {
    file: "/arabalar/renault-megane-3.jpg",
    artist: "Charles01",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Renault_M%C3%A9gane_III_diesel_1461cc_registered_December_2016.jpg",
  },
  "toyota-corolla-e140": {
    file: "/arabalar/toyota-corolla-e140.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2009_Toyota_Corolla_Altis_2.0_V_in_Medium_Silver,_front_right.jpg",
  },
  "honda-civic-fb": {
    file: "/arabalar/honda-civic-fb.jpg",
    artist: "Elise240SX",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2012_Honda_Civic_EX-L_Sedan_in_Taffeta_White,_front_right,_2025-06-14.jpg",
  },
  "vw-golf-mk6": {
    file: "/arabalar/vw-golf-mk6.jpg",
    artist: "M 93",
    license: "CC BY-SA 3.0 de",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:VW_Golf_1.6_TDI_Style_(VI)_%E2%80%93_Frontansicht,_25._Februar_2012,_Ratingen.jpg",
  },
  "nissan-qashqai-j10": {
    file: "/arabalar/nissan-qashqai-j10.jpg",
    artist: "Spurzem - Lothar Spurzem",
    license: "CC BY-SA 2.0 de",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/de/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nissan_Qashqai,_Bj._2008_-_Front_(2008-09-21_ret).jpg",
  },
  "fiat-linea": {
    file: "/arabalar/fiat-linea.jpg",
    artist: "Kevauto",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2007_Fiat_Linea,_front_8.3.18.jpg",
  },
  "hyundai-i30-fd": {
    file: "/arabalar/hyundai-i30-fd.jpg",
    artist: "JamesYoung8167",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hyundai_i30_FD_Shishi_01_2022-06-24.jpg",
  },
  "mazda-3-bl": {
    file: "/arabalar/mazda-3-bl.jpg",
    artist: "OSX",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2009_Mazda3_(BL)_SP25_sedan_(2009-11-14)_02.jpg",
  },
  "seat-ibiza-6j": {
    file: "/arabalar/seat-ibiza-6j.jpg",
    artist: "M 93",
    license: "CC BY-SA 3.0 de",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Seat_Ibiza_Copa_(6J)_%E2%80%93_Frontansicht,_10._September_2011,_D%C3%BCsseldorf.jpg",
  },
  "peugeot-308-t7": {
    file: "/arabalar/peugeot-308-t7.jpg",
    artist: "M 93",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Peugeot_308_3-T%C3%BCrer_front-1.JPG",
  },
  "kia-ceed-ed": {
    file: "/arabalar/kia-ceed-ed.jpg",
    artist: "Tanzania",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kia_ceed.jpg",
  },
  "skoda-octavia-3": {
    file: "/arabalar/skoda-octavia-3.jpg",
    artist: "JamesYoung8167",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%C5%A0koda_Octavia_III_Sanming_01_2022-08-13.jpg",
  },
  "opel-insignia-a": {
    file: "/arabalar/opel-insignia-a.jpg",
    artist: "Makizox",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2012_Vauxhall_Insignia_Exclusiv_1.8.jpg",
  },
  "toyota-auris-e150": {
    file: "/arabalar/toyota-auris-e150.jpg",
    artist: "M 93",
    license: "CC BY-SA 3.0 de",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Toyota_Auris_Life_(Facelift)_%E2%80%93_Frontansicht,_18._M%C3%A4rz_2012,_Wuppertal.jpg",
  },
  "renault-fluence": {
    file: "/arabalar/renault-fluence.jpg",
    artist: "Rutger van der Maar",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Renault_Fluence_front.jpg",
  },
  "vw-t-roc": {
    file: "/arabalar/vw-t-roc.jpg",
    artist: "Vauxford",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2018_Volkswagen_T-Roc_Front_(2).jpg",
  },
  "hyundai-tucson-nx4": {
    file: "/arabalar/hyundai-tucson-nx4.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hyundai_Tucson_(NX4,_SWB)_IMG_9135.jpg",
  },
  "kia-sportage-nq5": {
    file: "/arabalar/kia-sportage-nq5.jpg",
    artist: "Benespit",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2023_Kia_Sportage_(NQ5)_in_White,_front_left.jpg",
  },
  "peugeot-3008-2": {
    file: "/arabalar/peugeot-3008-2.jpg",
    artist: "© M 93",
    license: "CC BY-SA 3.0 de",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Peugeot_3008_THP_165_EAT6_Allure_GT-Line_(II)_%E2%80%93_Frontansicht_(1),_20._September_2017,_D%C3%BCsseldorf.jpg",
  },
  "ford-kuga-3": {
    file: "/arabalar/ford-kuga-3.jpg",
    artist: "© M 93",
    license: "CC BY-SA 3.0 de",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ford_Kuga_2.5_Duratec_FHEV_AWD_Active_(III,_Facelift)_%E2%80%93_f_01012025.jpg",
  },
  "skoda-karoq": {
    file: "/arabalar/skoda-karoq.jpg",
    artist: "Vauxford",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2018_Skoda_Karoq_SE_TSi_S-A_1.0_Front.jpg",
  },
  "toyota-rav4-xa50": {
    file: "/arabalar/toyota-rav4-xa50.jpg",
    artist: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Toyota_RAV4_Hybrid_(XA50)_DSC_2709.jpg",
  },
  "nissan-juke-f16": {
    file: "/arabalar/nissan-juke-f16.jpg",
    artist: "Harvey Bold",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2020_Nissan_Juke_Tekna_DIG-T_-_999cc_1.0_(117PS)_Petrol_-_Flame_Red_-_05-2024,_Front.jpg",
  },
  "citroen-c3-aircross": {
    file: "/arabalar/citroen-c3-aircross.jpg",
    artist: "Vauxford",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2018_Citroen_C3_Aircross_Flair_Puretec_1.2_Front.jpg",
  },
  "opel-mokka-b": {
    file: "/arabalar/opel-mokka-b.jpg",
    artist: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Opel_Mokka_B_1X7A0317.jpg",
  },
  "seat-ateca": {
    file: "/arabalar/seat-ateca.jpg",
    artist: "Charles01",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Seat_Ateca_2016_in_Hertfordshire.jpg",
  },
  "volvo-xc40": {
    file: "/arabalar/volvo-xc40.jpg",
    artist: "Vauxford",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2018_Volvo_XC40_First_Edition_T5_AWD_Automatic_2.0_Front.jpg",
  },
  "bmw-x3-g01": {
    file: "/arabalar/bmw-x3-g01.jpg",
    artist: "Dinkun Chen",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BMW_X3_(G01)_China_(13).jpg",
  },
  "mercedes-glc-x254": {
    file: "/arabalar/mercedes-glc-x254.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_GLC_220_d_4MATIC_(X254)_front.jpg",
  },
  "audi-q5-fy": {
    file: "/arabalar/audi-q5-fy.jpg",
    artist: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Audi_Q5_FY_Facelift_IMG_4139.jpg",
  },
  "jeep-compass-mp": {
    file: "/arabalar/jeep-compass-mp.jpg",
    artist: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jeep_Compass_(MP)_PHEV_Facelift_1X7A0140.jpg",
  },
  "mazda-cx5-kf": {
    file: "/arabalar/mazda-cx5-kf.jpg",
    artist: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mazda_CX-5_(KF)_Facelift_1X7A0331_(2).jpg",
  },
  "renault-captur-2": {
    file: "/arabalar/renault-captur-2.jpg",
    artist: "Guillaume Vachey",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Renault_Captur_II_(front).jpg",
  },
  "bmw-3-g20": {
    file: "/arabalar/bmw-3-g20.jpg",
    artist: "Dinkun Chen",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BMW_3_SERIES_LWB_SEDAN_(G20)_China_(15).jpg",
  },
  "mercedes-c-w206": {
    file: "/arabalar/mercedes-c-w206.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Mercedes-Benz_W206_C180_Avantgarde_in_Mojave_Silver,_front_right,_07-10-2024.jpg",
  },
  "audi-a4-b9": {
    file: "/arabalar/audi-a4-b9.jpg",
    artist: "Thomas doerfer",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Audi_A4_B9_Limousine_3.0_TDI_quattro.JPG",
  },
  "vw-passat-b8": {
    file: "/arabalar/vw-passat-b8.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Volkswagen_Passat_2.0TSI_R-Line_(B8)_front.jpg",
  },
  "skoda-superb-3": {
    file: "/arabalar/skoda-superb-3.jpg",
    artist: "JamesYoung8167",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%C5%A0koda_Superb_III_Shishi_01_2022-06-25.jpg",
  },
  "volvo-s60-3": {
    file: "/arabalar/volvo-s60-3.jpg",
    artist: "Herranderssvensson",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2019_Volvo_S60_01.jpg",
  },
  "lexus-is-xe30": {
    file: "/arabalar/lexus-is-xe30.jpg",
    artist: "Dinkun Chen",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:LEXUS_IS_300_(XE30)_China.jpg",
  },
  "alfa-romeo-giulia": {
    file: "/arabalar/alfa-romeo-giulia.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alfa_Romeo_Giulia_952_Veloce_Banchise_White_01.jpg",
  },
  "genesis-g70": {
    file: "/arabalar/genesis-g70.jpg",
    artist: "Benespit",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:0_Genesis_G70_1.jpg",
  },
  "jaguar-xe": {
    file: "/arabalar/jaguar-xe.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jaguar_XE_20t_PRESTIGE_(X760)_front.jpg",
  },
  "peugeot-508-2": {
    file: "/arabalar/peugeot-508-2.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Peugeot_508_GT_BlueHDi_(3DA-R8AH01)_front.jpg",
  },
  "mazda-6-gj": {
    file: "/arabalar/mazda-6-gj.jpg",
    artist: "EurovisionNim",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2014_Mazda_6_(GJ)_Sports_sedan_(2015-11-07)_01.jpg",
  },
  "opel-insignia-b": {
    file: "/arabalar/opel-insignia-b.jpg",
    artist: "Rutger van der Maar",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Opel_Insignia_GSi_Grand_Sport_Edition_Bitter_(48807830348).jpg",
  },
  "toyota-camry-xv70": {
    file: "/arabalar/toyota-camry-xv70.jpg",
    artist: "Dinkun Chen",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:TOYOTA_CAMRY_(XV70)_China.jpg",
  },
  "honda-accord-cv": {
    file: "/arabalar/honda-accord-cv.jpg",
    artist: "Kevauto",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2018_Honda_Accord_front_3.29.18.jpg",
  },
  "bmw-5-g30": {
    file: "/arabalar/bmw-5-g30.jpg",
    artist: "Dinkun Chen",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BMW_5_SERIES_LWB_SEDAN_(BMW_G38)_China_(66).jpg",
  },
  "mercedes-e-w213": {
    file: "/arabalar/mercedes-e-w213.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_W213_E200_2020.jpg",
  },
  "audi-a6-c8": {
    file: "/arabalar/audi-a6-c8.jpg",
    artist: "User3204",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2019_FAW-Audi_A6_L_(front).jpg",
  },
  "jeep-wrangler-jl": {
    file: "/arabalar/jeep-wrangler-jl.jpg",
    artist: "Dinkun Chen",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:JEEP_WRANGLER_(JL)_China.jpg",
  },
  "land-rover-defender-l663": {
    file: "/arabalar/land-rover-defender-l663.jpg",
    artist: "Aos.1905",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Land_Rover_Defender_110_(L663)_(front_view)_at_Grand_Green_Osaka.jpg",
  },
  "mercedes-g-w463": {
    file: "/arabalar/mercedes-g-w463.jpg",
    artist: "Vauxford",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2018_Mercedes-AMG_G_63_4MATIC_Automatic_4.0_Front.jpg",
  },
  "toyota-land-cruiser-j300": {
    file: "/arabalar/toyota-land-cruiser-j300.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2023_Toyota_Land_Cruiser_3.3_ZX_in_Attitude_Black_Mica,_front_right.jpg",
  },
  "ford-bronco-u725": {
    file: "/arabalar/ford-bronco-u725.jpg",
    artist: "SsmIntrigue",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2021_Ford_Bronco_Big_Bend,_Front_Right,_07-11-2021.jpg",
  },
  "suzuki-jimny-jb74": {
    file: "/arabalar/suzuki-jimny-jb74.jpg",
    artist: "EurovisionNim",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Suzuki_Jimny,_2020_front_01.jpg",
  },
  "nissan-patrol-y62": {
    file: "/arabalar/nissan-patrol-y62.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nissan_PATROL_(Y62)_front.JPG",
  },
  "jeep-grand-cherokee-wl": {
    file: "/arabalar/jeep-grand-cherokee-wl.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jeep_Grand_Cherokee_(WL)_IMG_7791.jpg",
  },
  "range-rover-l460": {
    file: "/arabalar/range-rover-l460.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Range_Rover_L460_HSE_Belgravia_Green_Metallic_-_front.jpg",
  },
  "toyota-hilux-an120": {
    file: "/arabalar/toyota-hilux-an120.jpg",
    artist: "Bull-Doser",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Toyota_HiLux_AN120-AN130_Crew_Cab.jpg",
  },
  "ford-ranger-raptor": {
    file: "/arabalar/ford-ranger-raptor.jpg",
    artist: "JoachimKohler-HB",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ford_Ranger_Raptor_-_20231003-P1003802.jpg",
  },
  "vw-amarok-2": {
    file: "/arabalar/vw-amarok-2.jpg",
    artist: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Volkswagen_Amarok_Mk2_Auto_Zuerich_2023_1X7A1337.jpg",
  },
  "isuzu-d-max-rg": {
    file: "/arabalar/isuzu-d-max-rg.jpg",
    artist: "Zotyefan",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Isuzu_D-Max_III_IMG001.jpg",
  },
  "mitsubishi-l200-2019": {
    file: "/arabalar/mitsubishi-l200-2019.jpg",
    artist: "Vauxford",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2019_Mitsubishi_L200_Warrior_DI-D_2.3_Front.jpg",
  },
  "land-rover-discovery-l462": {
    file: "/arabalar/land-rover-discovery-l462.jpg",
    artist: "Makizox",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2017_Land_Rover_Discovery_HSE_TD6_Automatic_Front.jpg",
  },
  "lexus-lx-j310": {
    file: "/arabalar/lexus-lx-j310.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lexus_LX_600_VJA310_Sonic_Quartz_-_front.jpg",
  },
  "ineos-grenadier": {
    file: "/arabalar/ineos-grenadier.jpg",
    artist: "Max B",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2021_Ineos_Grenadier_3.0_Front.jpg",
  },
  "dacia-duster-3": {
    file: "/arabalar/dacia-duster-3.jpg",
    artist: "Corvettec6r",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2024_Dacia_Duster_front.jpg",
  },
  "toyota-gr86": {
    file: "/arabalar/toyota-gr86.jpg",
    artist: "Elise240SX",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2022_Toyota_GR86_Premium_in_Halo,_Front_Right,_04-10-2022.jpg",
  },
  "subaru-brz-zd8": {
    file: "/arabalar/subaru-brz-zd8.jpg",
    artist: "Mr.choppers",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2022_Subaru_BRZ_Limited_in_Crystal_Black_Silica,_front_right_(NYIAS_2022).jpg",
  },
  "toyota-gt86": {
    file: "/arabalar/toyota-gt86.jpg",
    artist: "Fiver, der Hellseher",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Red_Toyota_GT86_(front).jpg",
  },
  "mazda-mx5-nd": {
    file: "/arabalar/mazda-mx5-nd.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mazda_MX-5_ND_35th_Anniversary_Edition_Convertible_Artisan_Red_Premium_-_front.jpg",
  },
  "nissan-z-rz34": {
    file: "/arabalar/nissan-z-rz34.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nissan_Fairlady_Z_Version_ST_(3BA-RZ34)_front.jpg",
  },
  "nissan-370z": {
    file: "/arabalar/nissan-370z.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nissan_370Z_Z34_2021_(1).jpg",
  },
  "subaru-wrx-vb": {
    file: "/arabalar/subaru-wrx-vb.jpg",
    artist: "MercurySable99",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2022_Subaru_WRX,_front_right,_06-19-2023.jpg",
  },
  "subaru-impreza-sti-gr": {
    file: "/arabalar/subaru-impreza-sti-gr.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Subaru_IMPREZA_WRX_STI_(GRB)_front.JPG",
  },
  "mitsubishi-evo-x": {
    file: "/arabalar/mitsubishi-evo-x.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mitsubishi_LANCER_GSR_EVOLUTION_X_(CBA-CZ4A)_front.JPG",
  },
  "honda-nsx-nc1": {
    file: "/arabalar/honda-nsx-nc1.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Honda_NSX_(4AA-NC1)_front.jpg",
  },
  "honda-civic-type-r-fk2": {
    file: "/arabalar/honda-civic-type-r-fk2.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Honda_CIVIC_TYPE_R_(DBA-FK2)_front.JPG",
  },
  "honda-civic-type-r-fd2": {
    file: "/arabalar/honda-civic-type-r-fd2.jpg",
    artist: "Corsadent56709",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:FD2_Honda_Civic_Type_R_in_Sham_Shui_Po.jpg",
  },
  "lexus-lc500": {
    file: "/arabalar/lexus-lc500.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2023_Lexus_LC_500_in_White_Nova_Glass_Flake,_front_right.jpg",
  },
  "lexus-rcf": {
    file: "/arabalar/lexus-rcf.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2015_Lexus_RC_F_in_Ultra_White,_front_right.jpg",
  },
  "lexus-isf": {
    file: "/arabalar/lexus-isf.jpg",
    artist: "Luftfahrrad",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lexus_IS-F_front.JPG",
  },
  "mazda-3-mps": {
    file: "/arabalar/mazda-3-mps.jpg",
    artist: "Calreyn88",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2012_Mazda_3_MPS.jpg",
  },
  "nissan-juke-nismo": {
    file: "/arabalar/nissan-juke-nismo.png",
    artist: "LukaCali",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2013_Nissan_Juke_Nismo_Front_Left.png",
  },
  "suzuki-swift-sport-zc32": {
    file: "/arabalar/suzuki-swift-sport-zc32.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Suzuki_SWIFT_sport_(ZC32S)_front.JPG",
  },
  "toyota-supra-a80": {
    file: "/arabalar/toyota-supra-a80.jpg",
    artist: "User3204",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1996_Toyota_Supra_A80_(front).jpg",
  },
  "nissan-skyline-r34": {
    file: "/arabalar/nissan-skyline-r34.jpg",
    artist: "Calreyn88",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2001_Nissan_Skyline_GT-R_V-Spec_II_R34_(79241).jpg",
  },
  "mazda-rx7-fd": {
    file: "/arabalar/mazda-rx7-fd.jpg",
    artist: "Mr.choppers",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1994_Mazda_RX-7_R2_in_Vintage_Red,_front_left_(Lime_Rock).jpg",
  },
  "honda-s2000": {
    file: "/arabalar/honda-s2000.jpg",
    artist: "Lukasz19930915",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Honda_S2000_AP1_prz%C3%B3d.JPG",
  },
  "nissan-silvia-s15": {
    file: "/arabalar/nissan-silvia-s15.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nissan_Silvia_S15_Spec_S,_front_left,_07-28-2024.jpg",
  },
  "honda-integra-dc2": {
    file: "/arabalar/honda-integra-dc2.jpg",
    artist: "Ths",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Honda_Integra_Type_R_DC2.JPG",
  },
  "bmw-m3-e46": {
    file: "/arabalar/bmw-m3-e46.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BMW_M3_CSL_(E46)_front.JPG",
  },
  "audi-rs4-b5": {
    file: "/arabalar/audi-rs4-b5.jpg",
    artist: "Rutger van der Maar",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2000_Audi_RS4_Avant_(B5)_front.jpg",
  },
  "renault-clio-v6": {
    file: "/arabalar/renault-clio-v6.jpg",
    artist: "Calreyn88",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2002_Renault_Clio_V6.jpg",
  },
  "ford-focus-rs-mk1": {
    file: "/arabalar/ford-focus-rs-mk1.jpg",
    artist: "Calreyn88",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2002_Ford_Focus_RS_(44438).jpg",
  },
  "honda-civic-ep3": {
    file: "/arabalar/honda-civic-ep3.jpg",
    artist: "Ethan Llamas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2002_Honda_Civic_Type_R_EP3,_front_right.jpg",
  },
  "subaru-impreza-sti-gd": {
    file: "/arabalar/subaru-impreza-sti-gd.jpg",
    artist: "Corsadent56709",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2002_Subaru_Impreza_WRX_STI_(GD),_Lok_Wah_North_Estate_(Front).jpg",
  },
  "chevrolet-corvette-c5": {
    file: "/arabalar/chevrolet-corvette-c5.jpg",
    artist: "Tokumeigakarinoaoshima",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chevrolet_CORVETTE_C5_front.JPG",
  },
  "chevrolet-camaro-4": {
    file: "/arabalar/chevrolet-camaro-4.jpg",
    artist: "Kroelleboelle",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1998_Chevrolet_Camaro_Front.jpg",
  },
  "mercedes-s-w140": {
    file: "/arabalar/mercedes-s-w140.jpg",
    artist: "M.rJirapat",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_S500_(W140)_Front.jpg",
  },
  "bmw-7-e38": {
    file: "/arabalar/bmw-7-e38.jpg",
    artist: "M 93",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BMW_7er_(E38)_20090314_front.jpg",
  },
  "lexus-ls400": {
    file: "/arabalar/lexus-ls400.jpg",
    artist: "M.rJirapat",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lexus_LS_400_in_Thailand_Front.jpg",
  },
  "alfa-romeo-156-gta": {
    file: "/arabalar/alfa-romeo-156-gta.jpg",
    artist: "FotoSleuth",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alfa_Romeo_156_GTA_(40920850890).jpg",
  },
};

// Kartın altında küçük punto ile görünen satır (SPEC 12.4).
export function photoCredit(slug) {
  const photo = PHOTOS[slug];
  return photo ? `${photo.artist} · ${photo.license}` : "";
}
